### ISSUE TITLE
Paclet Server Integration

### ISSUE THREAD

**Issue by b3m2a1** [zbjornson/MongoDBLink#16]
I was wondering if you'd want to add your package to the [Paclet Server / Package Repo](https://paclets.github.io/PacletServer/) I've set up for the general Mathematica community. Per [this](https://github.com/paclets/PacletServer/issues/35) I'm trying to increase awareness and get more paclets on the server so that more people can benefit from it.

I can handle any initial reformatting necessary to make everything work right, and I'll submit a pull request with any changes.

**Comment by zbjornson** [comment]
This repo is actually no longer active since Mathematica has built-in support now (#15). I need to update the readme to indicate that.

I do have https://github.com/zbjornson/MYaml, which is listed on http://packagedata.net/index.php/links/index/sort/newest/keyword/YAML/has_examples/false/has_download/false. That could be a good one to submit?

**Comment by b3m2a1** [comment]
Sounds good to me. I missed that one in my scrape because it didn't have the PacletInfo.m file. With your permission I'll make the appropriate additions to get it onto the server and then submit a PR.

**Comment by zbjornson** [comment]
Sounds great! Thanks :)
